<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">
	<!-- Import complex parts for robot -->
	<xacro:include filename="$(find dyret_description)/urdf/body.urdf.xacro" />
	<xacro:include filename="$(find dyret_description)/urdf/leg.urdf.xacro" />

	<xacro:macro name="dyret_robot">
		<xacro:body name="main_body" />

		<xacro:leg name="fl" />
		<joint name="fl_body_fixed" type="fixed">
			<parent link="main_body_chassis" />
			<child link="fl_joint1_servo" />
			<origin xyz="${-body_width / 2 + mx64at_width/2 - 0.007}
				${body_depth / 2 - mx64at_depth / 2 + 0.0065}
				${-mx64at_height}" />
		</joint>

		<xacro:leg name="fr" />
		<joint name="fr_body_fixed" type="fixed">
			<parent link="main_body_chassis" />
			<child link="fr_joint1_servo" />
			<origin xyz="${body_width / 2 - mx64at_width/2 + 0.012}
				${body_depth / 2 - mx64at_depth / 2 + 0.005}
				${-mx64at_height}" />
		</joint>

		<xacro:leg name="bl" />
		<joint name="bl_body_fixed" type="fixed">
			<parent link="main_body_chassis" />
			<child link="bl_joint1_servo" />
			<origin xyz="${-body_width / 2 + mx64at_width/2 - 0.01}
				${-body_depth / 2 + mx64at_depth / 2 - 0.0035}
				${-mx64at_height}" />
		</joint>

		<xacro:leg name="br" />
		<joint name="br_body_fixed" type="fixed">
			<parent link="main_body_chassis" />
			<child link="br_joint1_servo" />
			<origin xyz="${body_width / 2 - mx64at_width/2 + 0.009}
				${-body_depth / 2 + mx64at_depth / 2 - 0.005}
				${-mx64at_height}" />
		</joint>
	</xacro:macro>
</robot>
