<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">
	<xacro:include filename="$(find dyret_description)/urdf/joints/mx106.urdf.xacro" />
	<xacro:include filename="$(find dyret_description)/urdf/joints/mx64at.urdf.xacro" />
	<xacro:include filename="$(find dyret_description)/urdf/joints/small_extend.urdf.xacro" />
	<xacro:include filename="$(find dyret_description)/urdf/joints/large_extend.urdf.xacro" />
	<xacro:include filename="$(find dyret_description)/urdf/joints/foot.urdf.xacro" />

	<!-- Macro for one leg of Dyret -->
	<xacro:macro name="leg" params="name">
		<xacro:mx64at_fr05h101 name="${name}_joint1"/>
		<xacro:mx106t_fr08h101 name="${name}_joint2"/>
		<joint name="${name}_joint1_2_fixed" type="fixed">
			<parent link="${name}_joint1_bracket" />
			<child link="${name}_joint2_bracket" />
			<origin xyz="0 0 ${-mx64at_height/2 - fr05h101_height - 0.001}"
				rpy="0 0 ${pi/2}" />
		</joint>

		<xacro:small_extender name="${name}_ext1" />
		<joint name="${name}_joint2_ext1_fixed" type="fixed">
			<parent link="${name}_joint2_servo" />
			<child link="${name}_ext1_inner" />
			<origin xyz="0 0 ${-mx106t_height/2 - fr08h101_height - small_ext_height/2}" />
		</joint>

		<xacro:mx106t_fr08h101_inv name="${name}_joint3" />
		<joint name="${name}_ext1_joint3_fixed" type="fixed">
			<parent link="${name}_ext1_outer" />
			<child link="${name}_joint3_servo" />
			<origin xyz="0 0.002 ${-small_ext_height/2 - small_ext2_height - mx106t_height/2}"
				rpy="0 0 ${-pi/2}" />
		</joint>

		<xacro:large_extender name="${name}_ext2" />
		<joint name="${name}_joint3_ext2_fixed" type="fixed">
			<parent link="${name}_joint3_bracket" />
			<child link="${name}_ext2_inner" />
			<origin xyz="0 0 ${-fr08h101_height - large_ext_height + 0.0145/2}" />
		</joint>

		<xacro:foot name="${name}" />
		<joint name="${name}_ext2_foot_fixed" type="fixed">
			<parent link="${name}_ext2_outer" />
			<child link="${name}_foot_cyl" />
			<origin xyz="0 0 ${-large_ext2_height - 0.0355/2}" />
		</joint>
	</xacro:macro>
</robot>
