<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">
	<xacro:include filename="$(find dyret_description)/urdf/inertias.urdf.xacro" />

	<xacro:property name="large_ext_width" value="0.0343" />
	<xacro:property name="large_ext_depth" value="0.0081" />
	<xacro:property name="large_ext_height" value="0.1505" />

	<xacro:property name="large_ext2_width" value="0.0436" />
	<xacro:property name="large_ext2_depth" value="0.0212" />
	<xacro:property name="large_ext2_height" value="0.1287" />

	<xacro:macro name="large_ext" params="name">
		<link name="${name}">
			<visual>
				<origin xyz="0 0 ${large_ext_height/2}" />
				<geometry>
					<box size="${large_ext_width} ${large_ext_depth} ${large_ext_height}" />
				</geometry>
			</visual>
			<collision>
				<origin xyz="0 0 ${large_ext_height/2}" />
				<geometry>
					<box size="${large_ext_width} ${large_ext_depth} ${large_ext_height}" />
				</geometry>
			</collision>
			<xacro:box_inertia mass="0.099" width="${large_ext_width}"
				length="${large_ext_depth}" height="${large_ext_height}"
				r="${pi/2}" />
		</link>
	</xacro:macro>

	<xacro:macro name="large_ext2" params="name rot:=1">
		<link name="${name}">
			<visual>
				<origin rpy="0 0 ${pi/2 * rot}"
					xyz="${(large_ext2_width * 2 - 0.009) * rot}
					${(-large_ext2_depth * 2 - 0.002) * rot}
					${-large_ext2_height * 1.5 + 0.005}" />
				<geometry>
					<mesh filename="package://dyret_description/meshes/EXT2_OUTER.STL"
						scale="0.001 0.001 0.001"/>
				</geometry>
			</visual>
			<collision>
				<origin xyz="0 0 ${-large_ext2_height/2}" />
				<geometry>
					<box size="${large_ext2_width} ${large_ext2_depth} ${large_ext2_height}" />
				</geometry>
			</collision>
			<xacro:box_inertia_inv mass="0.037" width="${large_ext2_width}"
				length="${large_ext2_depth}" height="${large_ext2_height}"
				r="${pi/2}" />
		</link>
	</xacro:macro>

	<xacro:macro name="large_extender" params="name rot:=1">
		<xacro:large_ext name="${name}_inner" />
		<xacro:large_ext2 name="${name}_outer" rot="${rot}" />
		<joint name="${name}" type="prismatic">
			<parent link="${name}_inner" />
			<child link="${name}_outer" />
			<axis xyz="0 0 1" />
			<origin xyz="0 0 ${large_ext_height - 0.0291}" />
			<limit
				lower="-0.100" upper="0.0"
				effort="100.0" velocity="0.00045" />
			<!--<dynamics damping="1.0" friction="80" />-->
		</joint>
		<gazebo reference="${name}">
			<implicitSpringDamper>1</implicitSpringDamper>
		</gazebo>
	</xacro:macro>
</robot>
