# Controller configuration for dyret inside Gazebo
dyret:
  # Configure joint state controller for publishing transforms for any moving joints
  joint_state_controller:
    type: "joint_state_controller/JointStateController"
    publish_rate: 30

  # Default PID values for effort controllers
  shared_pid: &spid
    p: 36.0
    i: 0.0
    d: 0.0

  # Definition of controllers:
  front_right_coxa_controller:
    type: effort_controllers/JointPositionController
    joint: front_right_coxa_joint
    pid: *spid
  front_left_coxa_controller:
    type: effort_controllers/JointPositionController
    joint: front_left_coxa_joint
    pid: *spid
  back_right_coxa_controller:
    type: effort_controllers/JointPositionController
    joint: back_right_coxa_joint
    pid: *spid
  back_left_coxa_controller:
    type: effort_controllers/JointPositionController
    joint: back_left_coxa_joint
    pid: *spid

  # Femur controllers:
  front_right_femur_controller:
    type: effort_controllers/JointPositionController
    joint: front_right_femur_joint
    pid: *spid
  front_left_femur_controller:
    type: effort_controllers/JointPositionController
    joint: front_left_femur_joint
    pid: *spid
  back_right_femur_controller:
    type: effort_controllers/JointPositionController
    joint: back_right_femur_joint
    pid: *spid
  back_left_femur_controller:
    type: effort_controllers/JointPositionController
    joint: back_left_femur_joint
    pid: *spid

  # Tibia controllers
  front_right_tibia_controller:
    type: effort_controllers/JointPositionController
    joint: front_right_tibia_joint
    pid: *spid
  front_left_tibia_controller:
    type: effort_controllers/JointPositionController
    joint: front_left_tibia_joint
    pid: *spid
  back_right_tibia_controller:
    type: effort_controllers/JointPositionController
    joint: back_right_tibia_joint
    pid: *spid
  back_left_tibia_controller:
    type: effort_controllers/JointPositionController
    joint: back_left_tibia_joint
    pid: *spid
